### ISSUE TITLE
Reorganize the project structure and Add README

### ISSUE THREAD

**Issue by youngjoon-lee** [dasbeerboot/go-everlast-storage#4]
Reorganize the project structure like below, so that we can open the entire project with IDE.
```
├── README
├── client
│   └── main.go
├── go.mod
├── go.sum
├── proto
│   └── file_manager.proto
└── server
    └── main.go
```

In the `README`, please describe:
- How to build the server and the client
   - + How to generate `*.pb.go` files from the `*.proto` file (You might need to write a simple bash script, or just a guide).
- How to run them

**Comment by dasbeerboot** [comment]
How come I JUST found it out? 😱😱😱 Will be back in action asap
